# Site settings
title: matsuda
description: matsuda is iOS and Ruby on Rails developer
twitter_username: mtsd
github_username: matsuda
instagram_username: matsuda

# Build settings
markdown: kramdown

# Custom
permalink: /:year/:month/:day/:title.html
